name: 'Setup and install'
description: 'Common setup steps for Actions'

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'

    - shell: bash
      run: npm ci

    # Add more steps here as needed
