version: '3.4'
services:
  integresql:
    image: ghcr.io/allaboutapps/integresql:v1.1.0
    ports:
      - '5000:5000'
    depends_on:
      - postgres
    environment:
      PGHOST: postgres
      PGUSER: root
      PGPASSWORD: root

  postgres:
    image: postgres:latest # should be the same version as used live
    # ATTENTION
    # fsync=off, synchronous_commit=off and full_page_writes=off
    # gives us a major speed up during local development and testing (~30%),
    # however you should NEVER use these settings in PRODUCTION unless
    # you want to have CORRUPTED data.
    # DO NOT COPY/PASTE THIS BLINDLY.
    # YOU HAVE BEEN WARNED.
    # Apply some performance improvements to pg as these guarantees are not needed while running locally
    command: "postgres -c 'shared_buffers=128MB' -c 'fsync=off' -c 'synchronous_commit=off' -c 'full_page_writes=off' -c 'max_connections=100' -c 'client_min_messages=warning'"
    expose:
      - '5432'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - postgres-volume:/var/lib/postgresql/data

volumes:
  postgres-volume: # declare a named volume to persist DB data
