packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@eslint/js': ^9.39.1
  '@hookform/resolvers': ^5.2.2
  '@types/node': ^24.10.4
  dd-trace: ^5.81.0
  dotenv-cli: ^11.0.0
  eslint: ^9.39.2
  pino: ^10.1.0
  pino-pretty: ^13.1.3
  prettier: ^3.7.4
  prisma-extension-kysely: ^3.0.0
  prisma-kysely: ^2.2.1
  react-aria-components: 1.13.0
  react-hook-form: ^7.69.0
  typescript: ^5.9.3
  zod: ^4.2.1

catalogs:
  next:
    '@next/env': 16.1.1
    '@next/eslint-plugin-next': 16.1.1
    next: 16.1.1
  oui:
    '@opengovsg/oui': 0.0.31
    '@opengovsg/oui-theme': 0.0.31
  playwright:
    '@playwright/test': 1.57.0
    playwright: 1.57.0
  prisma:
    '@prisma/adapter-pg': 7.2.0
    '@prisma/client': 7.2.0
    prisma: 7.2.0
  react:
    '@types/react': ^19.2.7
    '@types/react-dom': ^19.2.3
    react: ^19.2.3
    react-dom: ^19.2.3
  react-query5:
    '@tanstack/react-query': ^5.90.14
    '@tanstack/react-query-devtools': ^5.91.2
  storybook10:
    '@storybook/addon-a11y': ^10.1.11
    '@storybook/addon-docs': ^10.1.11
    '@storybook/addon-vitest': ^10.1.11
    '@storybook/nextjs-vite': ^10.1.11
    eslint-plugin-storybook: ^10.1.10
    storybook: ^10.1.11
    storybook-addon-vite-mock: ^1.1.1
  t3-env:
    '@t3-oss/env-core': ^0.13.8
    '@t3-oss/env-nextjs': ^0.13.8
  tailwindcss4:
    '@tailwindcss/postcss': ^4.1.18
    tailwindcss: ^4.1.18
  trpc:
    '@trpc/client': ^11.8.1
    '@trpc/server': ^11.8.1
    '@trpc/tanstack-react-query': ^11.8.1
  vitest:
    '@vitest/browser': 4.0.8
    '@vitest/browser-playwright': 4.0.8
    '@vitest/coverage-v8': 4.0.8
    vitest: 4.0.8

linkWorkspacePackages: true

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - next
  - '@next/env'
  - '@next/eslint-plugin-next'
  - react
  - react-dom
  - '@opengovsg/*'
  - storybook
  - '@storybook/*'
  - eslint-plugin-storybook

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - esbuild
  - prisma

overrides:
  '@types/minimatch': 5.1.2
  # Prevent inclusion of sharp-libvips-*, which uses a copyleft license
  '@img/sharp-libvips-darwin-arm64': '-'

patchedDependencies:
  prisma-extension-kysely@3.0.0: patches/prisma-extension-kysely@3.0.0.patch

publicHoistPattern:
  - '*prettier*'
  - '*eslint-plugin*'
  - '*@opengovsg/oui*'
  - '*prisma*'
  - pg
