packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@eslint/js': ^9.39.1
  '@types/node': ^24.10.1
  dotenv-cli: ^11.0.0
  eslint: ^9.39.1
  prettier: ^3.7.3
  prisma-extension-kysely: ^3.0.0
  prisma-kysely: ^2.2.1
  react-aria-components: 1.13.0
  react-hook-form: ^7.67.0
  typescript: ^5.9.3
  zod: ^4.1.13

catalogs:
  oui:
    '@opengovsg/oui': 0.0.23
    '@opengovsg/oui-theme': 0.0.23
  prisma:
    '@prisma/adapter-pg': ^7.0.0
    '@prisma/client': ^7.1.0
    '@prisma/client-runtime-utils': 7.0.1
    prisma: ^7.1.0
  next:
    '@next/env': 16.0.10
    '@next/eslint-plugin-next': 16.0.10
    next: 16.0.10
  react:
    '@types/react': ^19.2.7
    '@types/react-dom': ^19.2.3
    react: ^19.2.3
    react-dom: ^19.2.3
  react-query5:
    '@tanstack/react-query': ^5.90.11
    '@tanstack/react-query-devtools': ^5.91.1
  storybook10:
    '@storybook/addon-a11y': ^10.1.10
    '@storybook/addon-docs': ^10.1.10
    '@storybook/addon-vitest': ^10.1.10
    '@storybook/nextjs-vite': ^10.1.10
    eslint-plugin-storybook: ^10.1.10
    storybook: ^10.1.10
    storybook-addon-vite-mock: ^1.1.0
  t3-env:
    '@t3-oss/env-core': ^0.13.8
    '@t3-oss/env-nextjs': ^0.13.8
  tailwindcss4:
    '@tailwindcss/postcss': ^4.1.17
    tailwindcss: ^4.1.17
  trpc:
    '@trpc/client': ^11.7.2
    '@trpc/server': ^11.7.2
    '@trpc/tanstack-react-query': ^11.7.2
  vitest:
    '@vitest/browser': 4.0.8
    '@vitest/browser-playwright': 4.0.8
    '@vitest/coverage-v8': 4.0.8
    vitest: 4.0.8

linkWorkspacePackages: true

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - next
  - '@next/env'
  - '@next/eslint-plugin-next'
  - react
  - react-dom
  - storybook
  - '@storybook/*'
  - eslint-plugin-storybook

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - esbuild
  - prisma

overrides:
  '@types/minimatch': 5.1.2

patchedDependencies:
  '@prisma/client': patches/@prisma__client.patch
  prisma-extension-kysely@3.0.0: patches/prisma-extension-kysely@3.0.0.patch

publicHoistPattern:
  - '*prettier*'
  - '*eslint-plugin*'
  - '*@opengovsg/oui*'
  - '*prisma*'
  - pg
