packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@eslint/js': ^9.35.0
  '@types/node': ^22.18.8
  dotenv-cli: ^10.0.0
  eslint: ^9.35.0
  prettier: ^3.6.2
  react-aria-components: 1.13.0
  typescript: ^5.9.3
  zod: ^4.1.5

catalogs:
  oui:
    '@opengovsg/oui': 0.0.19
    '@opengovsg/oui-theme': 0.0.19
  react-query5:
    '@tanstack/react-query': ^5.90.2
    '@tanstack/react-query-devtools': ^5.90.2
  react19:
    '@types/react': ^19.2.4
    '@types/react-dom': ^19.2.3
    react: 19.2.0
    react-dom: 19.2.0
  t3-env:
    '@t3-oss/env-core': ^0.13.8
    '@t3-oss/env-nextjs': ^0.13.8
  tailwindcss4:
    '@tailwindcss/postcss': ^4.1.13
    tailwindcss: ^4.1.13
  trpc:
    '@trpc/client': ^11.5.1
    '@trpc/server': ^11.5.1
    '@trpc/tanstack-react-query': ^11.5.1
  storybook10:
    storybook: 10.0.7
    '@storybook/addon-a11y': 10.0.7
    '@storybook/addon-docs': 10.0.7
    '@storybook/addon-vitest': 10.0.7
    '@storybook/nextjs-vite': 10.0.7
    storybook-addon-vite-mock: ^1.1.0
    eslint-plugin-storybook: 10.0.7
  vitest:
    vitest: 4.0.8
    '@vitest/browser': 4.0.8
    '@vitest/browser-playwright': 4.0.8
    '@vitest/coverage-v8': 4.0.8

linkWorkspacePackages: true

onlyBuiltDependencies:
  - esbuild

overrides:
  '@types/minimatch': 5.1.2

publicHoistPattern:
  - '*prettier*'
  - '*eslint-plugin*'
  - '*@opengovsg/oui*'
  - '*prisma*'
  - 'pg'
