packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@eslint/js': ^9.35.0
  '@types/node': ^22.18.8
  dotenv-cli: ^10.0.0
  eslint: ^9.35.0
  prettier: ^3.6.2
  typescript: ^5.9.3
  zod: ^4.1.5
  react-aria-components: ^1.13.0

catalogs:
  oui:
    '@opengovsg/oui': 0.0.19
    '@opengovsg/oui-theme': 0.0.19
  trpc:
    '@trpc/client': ^11.5.1
    '@trpc/server': ^11.5.1
    '@trpc/tanstack-react-query': ^11.5.1
  react-query5:
    '@tanstack/react-query': ^5.90.2
    '@tanstack/react-query-devtools': ^5.90.2
  react19:
    '@types/react': ^19.1.12
    '@types/react-dom': ^19.1.9
    react: 19.1.1
    react-dom: 19.1.1
  t3-env:
    '@t3-oss/env-core': ^0.13.8
    '@t3-oss/env-nextjs': ^0.13.8
  tailwindcss4:
    '@tailwindcss/postcss': ^4.1.13
    tailwindcss: ^4.1.13

linkWorkspacePackages: true

onlyBuiltDependencies:
  - esbuild

overrides:
  '@types/minimatch': 5.1.2

publicHoistPattern:
  - '*prettier*' # see https://github.com/IanVS/prettier-plugin-sort-imports/issues/205#issuecomment-3139130510
  - '*eslint-plugin*'
  - typescript-eslint
