#### Render Blueprint specification: https://dashboard.render.com/blueprints ####
## 👇 Preview environments: https://render.com/docs/preview-environments ###
# previewsEnabled: true
## 👇 Automatically nuke the environment after X days of inactivity to reduce billing:
# previewsExpireAfterDays: 2
services:
  - type: web
    name: starter-kit-app
    env: node
    plan: free
    ## 👇 Specify the plan for the PR deployment:
    # previewPlan: starter
    ## 👇 Preview Environment Initialization script:
    # initialDeployHook: npm run db-seed
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/trpc/healthcheck
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: starter-kit-db
          property: connectionString

databases:
  - name: starter-kit-db
    plan: free
